// scripts/modules-guard.inline.ts
const modulesGuard = [
  "/* ===== Modules Guard: per-module, 14 days, no live kick ===== */",
  "(function(){",
  "  try { console.log('[ModulesGuard] loaded on', location.pathname); } catch(_) {}",

  // === Налаштування ===
  "  const PERIOD_MS = 14 * 86400e3;                    // 14 днів",
  "  const SALT = 'put-your-random-salt-here-8e5b9f-4b1c-9d77'; // зміни під свій проект",

  // Період
  "  const periodIndex = () => Math.floor(Date.now() / PERIOD_MS);",
  "  const periodEndISO = () => new Date(Math.ceil(Date.now() / PERIOD_MS) * PERIOD_MS).toISOString();",

  // Детермінований «хеш» (12 символів) — НЕ крипта, але стабільний
  "  const hashLike = (s) => { let h=0>>>0; for (let i=0;i<s.length;i++) h=(h*31 + s.charCodeAt(i))>>>0; const a=h.toString(36).padStart(7,'0'); const b=((h^0x9e3779b9)>>>0).toString(36).padStart(7,'0'); return (a+b).slice(0,12); };",

  // ==== Нормалізація назв модулів ====
  "  // Приймаємо: '1 модуль', 'Модуль 1 — ...', 'Модуль 3.1 — ...', '3.1 модуль', '2-модуль' тощо.",
  "  const normalizeModuleName = (name) => {",
  "    const s = (name || '').toLowerCase().replace(/\\u2014|—/g,'—').replace(/-/g,' ').replace(/\\s+/g,' ').trim();",
  "    let m = s.match(/^модуль\\s*([0-9]+(?:\\.[0-9]+)?)\\b/);",
  "    if (m) return 'модуль ' + m[1];",
  "    m = s.match(/^([0-9]+(?:\\.[0-9]+)?)\\s*модуль\\b/);",
  "    if (m) return 'модуль ' + m[1];",
  "    m = s.match(/модуль\\s*([0-9]+(?:\\.[0-9]+)?)/);",
  "    if (m) return 'модуль ' + m[1];",
  "    return s; // якщо не модуль — повернемо очищений рядок",
  "  };",
  "  const isModuleFolder = (name) => /^модуль\\s+[0-9]+(?:\\.[0-9]+)?$/.test(normalizeModuleName(name));",

  // ВИПРАВЛЕНО: шукаємо сегмент модуля серед УСІХ частин шляху (підтримка /test-quartz/2-модуль/...)
  "  const currentModuleFromURL = () => {",
  "    try {",
  "      const path = decodeURIComponent(location.pathname || '');",
  "      const parts = path.split('/').filter(Boolean).map(p => p.replace(/-/g,' '));",
  "      for (const seg of parts) {",
  "        const cand = normalizeModuleName(seg);",
  "        if (isModuleFolder(cand)) return cand;",
  "      }",
  "      return '';",
  "    } catch { return ''; }",
  "  };",

  // Домашня сторінка (працює на GitHub Pages з базовим префіксом)
  "  const computeHomePath = () => {",
  "    const parts = (location.pathname || '/').split('/').filter(Boolean);",
  "    if (parts.length === 0) return '/';",
  "    // якщо перший сегмент — repo-name і другий виглядає як модуль, вважай базою '/'+parts[0]+'/'",
  "    const looksModule = (seg) => isModuleFolder(normalizeModuleName(seg.replace(/-/g,' ')));",
  "    if (parts.length >= 2 && !looksModule(parts[0]) && looksModule(parts[1])) return '/' + parts[0] + '/';",
  "    // інакше корінь",
  "    return '/';",
  "  };",

  // ==== Паролі модульні, стабільні 14 днів ====
  "  const expectedPassword = (folderName) => hashLike(SALT + ':' + periodIndex() + ':' + normalizeModuleName(folderName));",

  // ==== Доступ (персист до кінця періоду) ====
  "  const accessKey = (folderName) => 'moduleAccess::' + normalizeModuleName(folderName) + '::p' + periodIndex();",
  "  const hasAccess = (folderName) => {",
  "    try {",
  "      const raw = localStorage.getItem(accessKey(folderName));",
  "      if (!raw) return false;",
  "      const d = JSON.parse(raw);",
  "      if (!d || !d.granted) return false;",
  "      const t = d.expiresAt ? new Date(d.expiresAt).getTime() : 0;",
  "      return !t || t >= Date.now();",
  "    } catch { return false; }",
  "  };",
  "  const grantAccess = (folderName) => {",
  "    localStorage.setItem(accessKey(folderName), JSON.stringify({ granted: true, expiresAt: periodEndISO() }));",
  "  };",

  // ==== Модалка (лише для кліку в Explorer) ====
  "  const showPasswordModal = (folderName) => new Promise((resolve) => {",
  "    let isDark=false; try {",
  "      isDark=(window.matchMedia&&window.matchMedia('(prefers-color-scheme: dark)').matches)||",
  "            document.documentElement.classList.contains('dark')||",
  "            document.body.classList.contains('dark');",
  "    } catch(e){}",
  "    const overlay=document.createElement('div');",
  "    Object.assign(overlay.style,{position:'fixed',inset:'0',background:isDark?'rgba(0,0,0,.45)':'rgba(0,0,0,.35)',zIndex:9998,backdropFilter:'blur(6px)',WebkitBackdropFilter:'blur(6px)'});",
  "    const box=document.createElement('div');",
  "    Object.assign(box.style,{position:'fixed',top:'50%',left:'50%',transform:'translate(-50%,-50%)',background:isDark?'#1f1f1f':'#111',color:'#fff',padding:'20px',borderRadius:'14px',boxShadow:'0 12px 36px rgba(0,0,0,.35)',width:'min(520px,92vw)',zIndex:9999,fontFamily:'inherit'});",
  "    const inputStyle='width:100%;box-sizing:border-box;padding:12px 14px;border:1px solid '+(isDark?'#333':'#444')+';border-radius:10px;background:'+(isDark?'#2a2a2a':'#1b1b1b')+';color:#fff;outline:none';",
  "    const primaryBtn='flex:1;padding:12px 14px;border:0;border-radius:10px;cursor:pointer;background:#3a3aff;color:#fff';",
  "    const secondaryBtn='flex:1;padding:12px 14px;border:0;border-radius:10px;cursor:pointer;background:'+(isDark?'#2a2a2a':'#2b2b33')+';color:#ddd';",
  "    const title = (isModuleFolder(folderName) ? normalizeModuleName(folderName) : 'модуль');",
  "    box.innerHTML = '<h3 style=\"margin:0 0 12px 0;color:#fff\">Введіть пароль для: <b>'+title+'</b></h3>' +",
  "      '<input id=\"module-pass\" type=\"password\" placeholder=\"Пароль\" style=\"'+inputStyle+'\">' +",
  "      '<div id=\"module-err\" style=\"color:#ff6б6б;margin:8px 0 0 0;display:none\">Невірний пароль</div>' +",
  "      '<div style=\"display:flex;gap:10px;margin-top:14px\">' +",
  "        '<button id=\"module-ok\" style=\"'+primaryBtn+'\">Увійти</button>' +",
  "        '<button id=\"module-cancel\" style=\"'+secondaryBtn+'\">Скасувати</button>' +",
  "      '</div>' +",
  "      '<div style=\"margin-top:10px;opacity:.85;font-size:.9em\">Доступ збережеться до кінця поточного періоду.</div>';",
  "    const cleanup=()=>{ document.body.style.overflow=''; overlay.remove(); box.remove(); };",
  "    document.body.append(overlay, box); document.body.style.overflow='hidden';",
  "    const input=box.querySelector('#module-pass'); const err=box.querySelector('#module-err');",
  "    const okBtn=box.querySelector('#module-ok'); const cancelBtn=box.querySelector('#module-cancel');",
  "    const submit=()=>{",
  "      const pass=(input&&input.value?input.value:'').trim();",
  "      if(pass===expectedPassword(folderName)){ cleanup(); resolve(true);} else { if(err) err.style.display='block'; }",
  "    };",
  "    okBtn && okBtn.addEventListener('click', submit);",
  "    input && input.addEventListener('keydown', (e)=>{ if(e && e.key==='Enter') submit(); });",
  "    cancelBtn && cancelBtn.addEventListener('click', ()=>{ cleanup(); resolve(false); });",
  "    overlay.addEventListener('click', ()=>{ cleanup(); resolve(false); });",
  "    input && input.focus();",
  "  });",

  // ==== Перехоплення кліків у Explorer (тільки модалка) ====
  "  document.addEventListener('click', async (ev) => {",
  "    const el=ev.target; if(!(el instanceof Element)) return;",
  "    const folderBtn=el.closest('.folder-button'); const folderTitle=el.closest('.folder-title');",
  "    if(!folderBtn && !folderTitle) return;",
  "    const titleEl=(folderTitle || (folderBtn?folderBtn.querySelector('.folder-title'):null));",
  "    const folderNameRaw=(titleEl && titleEl.textContent?titleEl.textContent:'').trim();",
  "    const folderName=normalizeModuleName(folderNameRaw);",
  "    if(!isModuleFolder(folderName)) return;",
  "    if(hasAccess(folderName)) return;",
  "    ev.preventDefault(); ev.stopPropagation();",
  "    const ok=await showPasswordModal(folderName);",
  "    if(ok){",
  "      grantAccess(folderName);",
  "      requestAnimationFrame(()=>{ const target=folderBtn||folderTitle; if(target) target.dispatchEvent(new MouseEvent('click',{bubbles:true})); });",
  "    }",
  "  }, true);",

  // ==== Прямий вхід на модуль/крок — редірект без модалки ====",
  "  (function(){",
  "    const mod=currentModuleFromURL();",
  "    if(mod && isModuleFolder(mod) && !hasAccess(mod)){",
  "      const HOME = computeHomePath();",
  "      try{ location.replace(HOME); }catch(_){ location.href = HOME; }",
  "    }",
  "  })();",

  // ==== Хоткей: Ctrl+Alt+G — показати пароль для поточного модуля (або запитає назву) ====",
  "  document.addEventListener('keydown', (e)=>{",
  "    if(!(e.ctrlKey && e.altKey && e.key)) return;",
  "    const key = e.key.toLowerCase();",
  "    if(key==='g'){",
  "      let name = currentModuleFromURL();",
  "      if(!isModuleFolder(name)){",
  "        const typed = prompt('Вкажіть назву модуля (напр.: 1 модуль або Модуль 1)') || '';",
  "        name = normalizeModuleName(typed);",
  "      }",
  "      if(!isModuleFolder(name)) return;",
  "      const pass = expectedPassword(name);",
  "      console.log('[ModulesGuard] Пароль для', name, '→', pass, '(період', periodIndex(), ')');",
  "    }",
  "  });",

  "})();",
].join("\n");
export default modulesGuard;
