// scripts/modules-guard.inline.ts
const modulesGuard = [
  "/* ===== Modules Guard: global (Explorer + FolderPage) ===== */",
  "(function(){",
  "  // === Налаштування періоду ===",
  "  const PERIOD_MS = 30_000; // 30 секунд (тест). Для прод: 14 * 86400e3",
  "  const SALT = 'put-your-random-salt-here-8e5b9f-4b1c-9d77';",
  "",
  "  const periodIndex = () => Math.floor(Date.now() / PERIOD_MS);",
  "  const periodEndISO = () => new Date(Math.ceil(Date.now() / PERIOD_MS) * PERIOD_MS).toISOString();",
  "",
  "  const hashLike = (s) => { let h = 0>>>0; for (let i=0;i<s.length;i++) h=(h*31+s.charCodeAt(i))>>>0; const a=h.toString(36).padStart(7,'0'); const b=((h^0x9e3779b9)>>>0).toString(36).padStart(7,'0'); return (a+b).slice(0,12) };",
  "",
  "  const getRotatingPasswordFor = (folderName) => hashLike(SALT+':'+periodIndex()+':'+folderName);",
  "  const getRotatingGlobalPassword = () => hashLike(SALT+':'+periodIndex()+':GLOBAL');",
  "  const PASSWORDS_PER_MODULE = { /* '1 модуль': 'manualM1pass' */ };",
  "  const expectedPassword = (folderName) => PASSWORDS_PER_MODULE[folderName] ?? getRotatingPasswordFor(folderName);",
  "",
  "  const accessKey = (folderName) => 'moduleAccess::'+folderName+'::p'+periodIndex();",
  "  const hasAccess = (folderName) => { try { const raw=localStorage.getItem(accessKey(folderName)); if(!raw) return false; const d=JSON.parse(raw); if(!d.granted) return false; const t=d.expiresAt?new Date(d.expiresAt).getTime():0; return !t || t>=Date.now(); } catch { return false; } };",
  "  const grantAccess = (folderName) => { localStorage.setItem(accessKey(folderName), JSON.stringify({granted:true, expiresAt:periodEndISO()})); };",
  "",
  "  const isModuleFolder = (name) => !!name && /^\\s*\\d+\\s*(модуль|module)/i.test(name.trim());",
  "  const currentModuleFromURL = () => { try { const path=decodeURIComponent(location.pathname||''); const first=path.replace(/^\\/+/, '').split('/')[0]||''; return first?first.replace(/-/g,' ').trim():''; } catch { return ''; } };",
  "  const computeHomePath = () => { const parts=(location.pathname||'/').split('/').filter(Boolean); if(parts.length===0 || /^\\d+/.test(parts[0])) return '/'; return '/'+parts[0]+'/'; };",
  "",
  "  const showPasswordModal = (folderName) => new Promise((resolve) => {",
  "    let isDark=false; try { isDark=(window.matchMedia&&window.matchMedia('(prefers-color-scheme: dark)').matches)||document.documentElement.classList.contains('dark')||document.body.classList.contains('dark'); } catch(e){}",
  "    const overlay=document.createElement('div'); Object.assign(overlay.style,{position:'fixed',inset:'0',background:isDark?'rgba(0,0,0,.45)':'rgba(0,0,0,.35)',zIndex:9998,backdropFilter:'blur(6px)',WebkitBackdropFilter:'blur(6px)'});",
  "    const box=document.createElement('div'); Object.assign(box.style,{position:'fixed',top:'50%',left:'50%',transform:'translate(-50%,-50%)',background:isDark?'#1f1f1f':'#111',color:'#fff',padding:'20px',borderRadius:'14px',boxShadow:'0 12px 36px rgba(0,0,0,.35)',width:'min(520px,92vw)',zIndex:9999,fontFamily:'inherit'});",
  "    const inputStyle='width:100%;box-sizing:border-box;padding:12px 14px;border:1px solid '+(isDark?'#333':'#444')+';border-radius:10px;background:'+(isDark?'#2a2a2a':'#1b1b1b')+';color:#fff;outline:none';",
  "    const primaryBtn='flex:1;padding:12px 14px;border:0;border-radius:10px;cursor:pointer;background:#3a3aff;color:#fff';",
  "    const secondaryBtn='flex:1;padding:12px 14px;border:0;border-radius:10px;cursor:pointer;background:'+(isDark?'#2a2a2a':'#2b2b33')+';color:#ddd';",
  "    box.innerHTML = '<h3 style=\"margin:0 0 12px 0;color:#fff\">Введіть пароль для: <b>'+folderName+'</b></h3>' +",
  "      '<input id=\"module-pass\" type=\"password\" placeholder=\"Пароль\" style=\"'+inputStyle+'\">' +",
  "      '<div id=\"module-err\" style=\"color:#ff6b6b;margin:8px 0 0 0;display:none\">Невірний пароль</div>' +",
  "      '<div style=\"display:flex;gap:10px;margin-top:14px\">' +",
  "        '<button id=\"module-ok\" style=\"'+primaryBtn+'\">Увійти</button>' +",
  "        '<button id=\"module-cancel\" style=\"'+secondaryBtn+'\">Скасувати</button>' +",
  "      '</div>' +",
  "      '<div style=\"margin-top:10px;opacity:.85;font-size:.9em\">Доступ збережеться до кінця поточного періоду.</div>';",
  "    const cleanup=()=>{ document.body.style.overflow=''; overlay.remove(); box.remove(); };",
  "    document.body.append(overlay, box); document.body.style.overflow='hidden';",
  "    const input=box.querySelector('#module-pass'); const err=box.querySelector('#module-err');",
  "    const okBtn=box.querySelector('#module-ok'); const cancelBtn=box.querySelector('#module-cancel');",
  "    const submit=()=>{ const pass=(input&&input.value?input.value:'').trim(); if(pass===expectedPassword(folderName) || pass===getRotatingGlobalPassword()){ cleanup(); resolve(true);} else { if(err) err.style.display='block'; } };",
  "    okBtn && okBtn.addEventListener('click', submit);",
  "    input && input.addEventListener('keydown', (e)=>{ if(e && e.key==='Enter') submit(); });",
  "    cancelBtn && cancelBtn.addEventListener('click', ()=>{ cleanup(); resolve(false); });",
  "    overlay.addEventListener('click', ()=>{ cleanup(); resolve(false); });",
  "    input && input.focus();",
  "  });",
  "",
  "  // Хук на кліки (Explorer)",
  "  document.addEventListener('click', async (ev) => {",
  "    const el = ev.target; if(!(el instanceof Element)) return;",
  "    const folderBtn = el.closest('.folder-button'); const folderTitle = el.closest('.folder-title');",
  "    if (!folderBtn && !folderTitle) return;",
  "    const titleEl = (folderTitle || (folderBtn ? folderBtn.querySelector('.folder-title') : null));",
  "    const folderName = (titleEl && titleEl.textContent ? titleEl.textContent : '').trim();",
  "    if (!isModuleFolder(folderName)) return;",
  "    if (hasAccess(folderName)) return;",
  "    ev.preventDefault(); ev.stopPropagation();",
  "    const ok = await showPasswordModal(folderName);",
  "    if (ok) { grantAccess(folderName); requestAnimationFrame(()=>{ const target=folderBtn||folderTitle; if(target) target.dispatchEvent(new MouseEvent('click',{bubbles:true})); }); }",
  "  }, true);",
  "",
  "  // Guard + live-enforcement (FolderPage, прямі лінки, протухання)",
  "  (function(){",
  "    const HOME = computeHomePath();",
  "    const askOrRedirect = (folderName) => {",
  "      const cover=document.createElement('div'); Object.assign(cover.style,{position:'fixed',inset:'0',zIndex:9997,background:'rgba(0,0,0,.5)',backdropFilter:'blur(8px)',WebkitBackdropFilter:'blur(8px)'});",
  "      document.body.append(cover); document.body.style.overflow='hidden';",
  "      showPasswordModal(folderName).then((ok)=>{ if(ok){ try{cover.remove();}catch(e){} document.body.style.overflow=''; grantAccess(folderName);} else { try{location.href=HOME;}catch(e){} } });",
  "    };",
  "    try { const mod0=currentModuleFromURL(); if(mod0 && isModuleFolder(mod0) && !hasAccess(mod0)) askOrRedirect(mod0); } catch(e){}",
  "    (function(){",
  "      let isPrompting=false;",
  "      const enforce=()=>{ try{ const mod=currentModuleFromURL(); if(!mod || !isModuleFolder(mod)) return; if(hasAccess(mod)) return; if(isPrompting) return; isPrompting=true; askOrRedirect(mod); setTimeout(()=>{isPrompting=false;},2000); }catch(e){} };",
  "      setInterval(enforce, 1000); document.addEventListener('visibilitychange', enforce); window.addEventListener('storage', enforce);",
  "    })();",
  "  })();",
  "",
  "  // Hotkeys у консоль",
  "  document.addEventListener('keydown', (e)=>{",
  "    try{ if(!(e.ctrlKey && e.altKey && e.key)) return; const key=e.key.toLowerCase();",
  "      if(key==='p'){",
  "        const inf=currentModuleFromURL();",
  "        const folderName = (inf && /^\\s*\\d+\\s*(модуль|module)/i.test(inf)) ? inf : ((prompt('Вкажіть назву модуля (наприклад: 2 модуль)')||'').trim());",
  "        if(!folderName) return; const pass=expectedPassword(folderName);",
  "        console.log('[ModulesGuard] Модуль:', folderName, '| Період:', periodIndex(), '| Пароль:', pass);",
  "        return;",
  "      }",
  "      if(key==='g'){",
  "        const g=getRotatingGlobalPassword();",
  "        console.log('[ModulesGuard] Глобальний пароль (12 символів):', g, '| Період:', periodIndex());",
  "        return;",
  "      }",
  "    }catch(_){}",
  "  });",
  "",
  "})();",
].join("\\n");
export default modulesGuard;
