// scripts/modules-guard.inline.ts
const modulesGuard = [
  "/* ===== Modules Guard: global (Explorer + FolderPage) ===== */",
  "(function(){",
  "  // === Налаштування періоду (14 днів) ===",
  "  const PERIOD_MS = 14 * 86400e3;",
  "  const SALT = 'put-your-random-salt-here-8e5b9f-4b1c-9d77';",
  "",
  "  const periodIndex = () => Math.floor(Date.now() / PERIOD_MS);",
  "  const periodEndISO = () => new Date(Math.ceil(Date.now() / PERIOD_MS) * PERIOD_MS).toISOString();",
  "",
  "  // простий детермінований «hash-like» (не крипта, як гейт достатньо)",
  "  const hashLike = (s) => { let h = 0>>>0; for (let i=0;i<s.length;i++) h = (h*31 + s.charCodeAt(i))>>>0; const a=h.toString(36).padStart(7,'0'); const b=((h^0x9e3779b9)>>>0).toString(36).padStart(7,'0'); return (a+b).slice(0,12); };",
  "",
  "  // Паролі (ротація кожні 14 днів)",
  "  const getRotatingPasswordFor = (folderName) => hashLike(SALT+':'+periodIndex()+':'+folderName);",
  "  const getRotatingGlobalPassword = () => hashLike(SALT+':'+periodIndex()+':GLOBAL');",
  "  const PASSWORDS_PER_MODULE = { /* '1 модуль': 'manualM1pass' */ }; // опційно ручні",
  "  const expectedPassword = (folderName) => PASSWORDS_PER_MODULE[folderName] ?? getRotatingPasswordFor(folderName);",
  "",
  "  // Доступ (кеш до кінця поточного періоду)",
  "  const accessKey = (folderName) => 'moduleAccess::'+folderName+'::p'+periodIndex();",
  "  const hasAccess = (folderName) => { try { const raw=localStorage.getItem(accessKey(folderName)); if(!raw) return false; const d=JSON.parse(raw); if(!d.granted) return false; const t=d.expiresAt?new Date(d.expiresAt).getTime():0; return !t || t>=Date.now(); } catch { return false; } };",
  "  const grantAccess = (folderName) => { localStorage.setItem(accessKey(folderName), JSON.stringify({ granted:true, expiresAt: periodEndISO() })); };",
  "",
  "  // Утиліти",
  "  const isModuleFolder = (name) => !!name && /^\\s*\\d+\\s*(модуль|module)/i.test(name.trim());",
  "  const currentModuleFromURL = () => { try { const path=decodeURIComponent(location.pathname||''); const first=path.replace(/^\\/+/, '').split('/')[0]||''; return first?first.replace(/-/g,' ').trim():''; } catch { return ''; } };",
  "  const computeHomePath = () => { const parts=(location.pathname||'/').split('/').filter(Boolean); if(parts.length===0 || /^\\d+/.test(parts[0])) return '/'; return '/'+parts[0]+'/'; };",
  "",
  "  // Модалка з блюром (білий текст для контрасту)",
  "  const showPasswordModal = (folderName) => new Promise((resolve) => {",
  "    let isDark=false; try { isDark=(window.matchMedia&&window.matchMedia('(prefers-color-scheme: dark)').matches)||document.documentElement.classList.contains('dark')||document.body.classList.contains('dark'); } catch(e){}",
  "    const overlay=document.createElement('div'); Object.assign(overlay.style,{position:'fixed',inset:'0',background:isDark?'rgba(0,0,0,.45)':'rgba(0,0,0,.35)',zIndex:9998,backdropFilter:'blur(6px)',WebkitBackdropFilter:'blur(6px)'});",
  "    const box=document.createElement('div'); Object.assign(box.style,{position:'fixed',top:'50%',left:'50%',transform:'translate(-50%,-50%)',background:isDark?'#1f1f1f':'#111',color:'#fff',padding:'20px',borderRadius:'14px',boxShadow:'0 12px 36px rgba(0,0,0,.35)',width:'min(520px,92vw)',zIndex:9999,fontFamily:'inherit'});",
  "    const inputStyle='width:100%;box-sizing:border-box;padding:12px 14px;border:1px solid '+(isDark?'#333':'#444')+';border-radius:10px;background:'+(isDark?'#2a2a2a':'#1b1b1b')+';color:#fff;outline:none';",
  "    const primaryBtn='flex:1;padding:12px 14px;border:0;border-radius:10px;cursor:pointer;background:#3a3aff;color:#fff';",
  "    const secondaryBtn='flex:1;padding:12px 14px;border:0;border-radius:10px;cursor:pointer;background:'+(isDark?'#2a2a2a':'#2b2b33')+';color:#ddd';",
  "    box.innerHTML = '<h3 style=\"margin:0 0 12px 0;color:#fff\">Введіть пароль для: <b>'+folderName+'</b></h3>' +",
  "      '<input id=\"module-pass\" type=\"password\" placeholder=\"Пароль\" style=\"'+inputStyle+'\">' +",
  "      '<div id=\"module-err\" style=\"color:#ff6b6b;margin:8px 0 0 0;display:none\">Невірний пароль</div>' +",
  "      '<div style=\"display:flex;gap:10px;margin-top:14px\">' +",
  "        '<button id=\"module-ok\" style=\"'+primaryBtn+'\">Увійти</button>' +",
  "        '<button id=\"module-cancel\" style=\"'+secondaryBtn+'\">Скасувати</button>' +",
  "      '</div>' +",
  "      '<div style=\"margin-top:10px;opacity:.85;font-size:.9em\">Доступ збережеться до кінця поточного періоду.</div>';",
  "    const cleanup=()=>{ document.body.style.overflow=''; overlay.remove(); box.remove(); };",
  "    document.body.append(overlay, box); document.body.style.overflow='hidden';",
  "    const input=box.querySelector('#module-pass'); const err=box.querySelector('#module-err');",
  "    const okBtn=box.querySelector('#module-ok'); const cancelBtn=box.querySelector('#module-cancel');",
  "    const submit=()=>{ const pass=(input&&input.value?input.value:'').trim(); if(pass===expectedPassword(folderName) || pass===getRotatingGlobalPassword()){ cleanup(); resolve(true);} else { if(err) err.style.display='block'; } };",
  "    okBtn && okBtn.addEventListener('click', submit);",
  "    input && input.addEventListener('keydown', (e)=>{ if(e && e.key==='Enter') submit(); });",
  "    cancelBtn && cancelBtn.addEventListener('click', ()=>{ cleanup(); resolve(false); });",
  "    overlay.addEventListener('click', ()=>{ cleanup(); resolve(false); });",
  "    input && input.focus();",
  "  });",
  "",
  "  // Хук на кліки (коли є Explorer)",
  "  document.addEventListener('click', async (ev) => { const el=ev.target; if(!(el instanceof Element)) return; const folderBtn=el.closest('.folder-button'); const folderTitle=el.closest('.folder-title'); if(!folderBtn && !folderTitle) return; const titleEl=(folderTitle || (folderBtn?folderBtn.querySelector('.folder-title'):null)); const folderName=(titleEl && titleEl.textContent?titleEl.textContent:'').trim(); if(!isModuleFolder(folderName)) return; if(hasAccess(folderName)) return; ev.preventDefault(); ev.stopPropagation(); const ok=await showPasswordModal(folderName); if(ok){ grantAccess(folderName); requestAnimationFrame(()=>{ const target=folderBtn||folderTitle; if(target) target.dispatchEvent(new MouseEvent('click',{bubbles:true})); }); } }, true);",
  "",
  "  // Guard + live-enforcement (працює навіть без Explorer)",
  "  (function(){",
  "    const HOME = computeHomePath();",
  "    const askOrRedirect = (folderName) => { const cover=document.createElement('div'); Object.assign(cover.style,{position:'fixed',inset:'0',zIndex:9997,background:'rgba(0,0,0,.5)',backdropFilter:'blur(8px)',WebkitBackdropFilter:'blur(8px)'}); document.body.append(cover); document.body.style.overflow='hidden'; showPasswordModal(folderName).then((ok)=>{ if(ok){ try{cover.remove();}catch(e){} document.body.style.overflow=''; grantAccess(folderName);} else { try{location.href=HOME;}catch(e){} } }); };",
  "    // одноразово при прямому вході",
  "    try { const mod0=currentModuleFromURL(); if(mod0 && isModuleFolder(mod0) && !hasAccess(mod0)) askOrRedirect(mod0); } catch(e){}",
  "    // live-перевірка (коли період змінився)",
  "    (function(){ let isPrompting=false; const enforce=()=>{ try{ const mod=currentModuleFromURL(); if(!mod || !isModuleFolder(mod)) return; if(hasAccess(mod)) return; if(isPrompting) return; isPrompting=true; askOrRedirect(mod); setTimeout(()=>{isPrompting=false;},2000); }catch(e){} }; setInterval(enforce,1000); document.addEventListener('visibilitychange', enforce); window.addEventListener('storage', enforce); })();",
  "  })();",
  "",
  "  // Хоткеї у консоль: Ctrl+Alt+P (модуль), Ctrl+Alt+G (глобальний), Ctrl+Alt+A (усі паролі на головній)",
  "  document.addEventListener('keydown', (e)=>{",
  "    try{",
  "      if(!(e.ctrlKey && e.altKey && e.key)) return;",
  "      const key = e.key.toLowerCase();",
  "",
  "      // ===== Ctrl + Alt + P → пароль для модуля (із URL або вручну) =====",
  "      if(key==='p'){",
  "        const inf=currentModuleFromURL();",
  "        const folderName=(inf && /^\\s*\\d+\\s*(модуль|module)/i.test(inf)) ? inf : ((prompt('Вкажіть назву модуля (наприклад: 2 модуль)')||'').trim());",
  "        if(!folderName) return;",
  "        const pass=expectedPassword(folderName);",
  "        console.log('[ModulesGuard] Модуль:', folderName, '| Період:', periodIndex(), '| Пароль:', pass);",
  "        return;",
  "      }",
  "",
  "      // ===== Ctrl + Alt + G → глобальний пароль (12 символів) =====",
  "      if(key==='g'){",
  "        const g=getRotatingGlobalPassword();",
  "        console.log('[ModulesGuard] Глобальний пароль (12 символів):', g, '| Період:', periodIndex());",
  "        return;",
  "      }",
  "",
  "      // ===== Ctrl + Alt + A → ВИВЕСТИ ВСІ ПАРОЛІ (тільки на головній) =====",
  "      if(key==='a'){",
  "        const isHome = (()=>{",
  "          const HOME = computeHomePath();",
  "          let p = location.pathname || '/';",
  "          if(!p.endsWith('/')) p += '/';",
  "          return p === HOME;",
  "        })();",
  "        if(!isHome){",
  "          console.warn('[ModulesGuard] Ctrl+Alt+A працює лише на головній сторінці сайту. Перейдіть на', computeHomePath());",
  "          return;",
  "        }",
  "",
  "        // Зібрати назви модулів з посилань на сторінці",
  "        const findModulesOnPage = ()=>{",
  "          const set = new Set();",
  "          document.querySelectorAll('a[href]')?.forEach((a)=>{",
  "            try{",
  "              const href = (a as HTMLAnchorElement).getAttribute('href') || '';",
  "              if(!href) return;",
  "              // нормалізуємо шлях, беремо перший сегмент",
  "              let path = href;",
  "              // абсолютні/відносні/якоря — усе приймаємо",
  "              if(/^https?:/i.test(path)){",
  "                try{ path = new URL(path).pathname; }catch(_){ return; }",
  "              }",
  "              const first = decodeURIComponent(path).replace(/^\\/+/, '').split('/')[0] || '';",
  "              if(!first) return;",
  "              const name = first.replace(/-/g,' ').trim(); // \"1-модуль\" -> \"1 модуль\"",
  "              if(isModuleFolder(name)) set.add(name);",
  "            }catch(_){ /* ignore */ }",
  "          });",
  "          // відсортуємо за номером модуля (якщо є)",
  "          const arr = Array.from(set);",
  "          arr.sort((a,b)=>{",
  "            const na = parseInt((a.match(/\\d+/)||['0'])[0],10);",
  "            const nb = parseInt((b.match(/\\d+/)||['0'])[0],10);",
  "            return na-nb || a.localeCompare(b,'uk');",
  "          });",
  "          return arr;",
  "        };",
  "",
  "        let modules = findModulesOnPage();",
  "        if(!modules.length){",
  "          // Фолбек: можна підставити руками, якщо на головній немає лінків на модулі",
  "          // Приклад: const MANUAL = ['1 модуль','2 модуль','3 модуль','4 модуль','5 модуль','6 модуль','7 модуль'];",
  "          const manual = prompt('[ModulesGuard] Не знайшов посилань на модулі. Вкажіть перелік через кому (напр.: 1 модуль,2 модуль,3 модуль):','');",
  "          if(manual){",
  "            modules = manual.split(',').map(s=>s.trim()).filter(Boolean);",
  "          }",
  "        }",
  "",
  "        if(!modules.length){",
  "          console.warn('[ModulesGuard] Немає модулів для виводу.');",
  "          return;",
  "        }",
  "",
  "        const table = modules.map((name)=>({",
  "          module: name,",
  "          password: (PASSWORDS_PER_MODULE[name] ?? expectedPassword(name))",
  "        }));",
  "        const g = getRotatingGlobalPassword();",
  "        console.log('[ModulesGuard] Період:', periodIndex());",
  "        console.log('[ModulesGuard] Глобальний пароль:', g);",
  "        console.table(table);",
  "        return;",
  "      }",
  "    }catch(_){}",
  "  });",

].join("\n");
export default modulesGuard;
